# 1D Numpy in Python

In [17]:
#List and Numpy array are similiar almost in major aspects. Now we look at an example 

import numpy as np

a = [1,4,5,6,7]
b = np.array(a[:]) #making copy of list 'a' to the numpy array 'b'
print("Note the difference of different output \n") #check the output of list 
print(a,"\n",b) #check the output of numpy array, "see the different"

Note the difference of different output 

[1, 4, 5, 6, 7] 
 [1 4 5 6 7]


In [11]:
#let's check the data type of both a and b

print("The type of variable 'a' is", type(a))
print("The type of variable 'b' is", type(b))

The type of variable 'a' is <class 'list'>
The type of variable 'b' is <class 'numpy.ndarray'>


In [18]:
#lets pull the value of each variable based on index value

print("a[0]:", a[0])
print("b[0]:", b[0])

a[0]: 1
b[0]: 1


In [23]:
#Let's see the combination of both

c = np.array([2,4,5,9,10]) #what can be the data type, guess ?
print(type(c))
print(c.dtype)

d = np.array([3.4,4.5,5.6,121.0,4.6])
print(type(d))
print(d.dtype)

<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
float64


In [27]:
#We can also change the value of numpy array directly using index

print("Before making changes the d[3]:", d[3])
d[3] = 12.1
print("After making changes the d[3]:", d[3])
print("The complete array now",d)

Before making changes the d[3]: 12.1
After making changes the d[3]: 12.1
The complete array now [  3.4   4.5   5.6  12.1   4.6]


In [36]:
# Will move to the SLICING topic

e = d[1:3] #1st value will e included and second value will be excluded
print(e)

[ 4.5  5.6]


In [42]:
e = np.append(8.5, 9.0)
e = np.append(e, [4.5, 5.6] )
e

array([ 8.5,  9. ,  4.5,  5.6])

In [44]:
select = [0,2,3] #This is the list of some values

#We are going to use the list as index for the np.array of 'e'

e[select] #See the output, it selects the value of indicies = 0,2,3 of 'e'

array([ 8.5,  4.5,  5.6])

In [47]:
#lets change all the values at the select indices with a common value

e[select] = 2.0

#Now check the "e"

e #Hope you got the point, what am trying to so.. !! This is called assign value with List

array([ 2.,  9.,  2.,  2.])

In [68]:
#Let's play the game with the functionalities of numpy like min, max, mean, standard deviation

a1 = np.array([1,3,4,5,8,9,4])
a1
b1 = np.array([2,100,30, 45])

In [69]:
a1.min()

1

In [70]:
a1.max()

9

In [71]:
a1.sort() # this sorted the original list
a1

array([1, 3, 4, 4, 5, 8, 9])

In [75]:
#whereas lets see the changes making for b1

b2 = sorted(b1)  #this is more important 
print("the b1 array is", b1)
print("the b2 array is", b2)

the b1 array is [  2 100  30  45]
the b2 array is [2, 30, 45, 100]


In [77]:
mean = a1.mean()
mean

4.8571428571428568

In [79]:
std = a1.std()
std

2.5872528966106905

In [82]:
#Will work on Numpy add, sub, mul & etc

print(a)
print(b)
print(c)

[1, 4, 5, 6, 7]
[1 4 5 6 7]
[ 2  4  5  9 10]


In [83]:
z = b + c

In [84]:
z

array([ 3,  8, 10, 15, 17])

In [88]:
#now multiplication

z1 = 2*a # here i used the list instead of numpy array, see the results and find the difference
print(z1) # here output replicated twice of same list

z2 = 2*b
print(z2) #numpy array got multiplied with 2

[1, 4, 5, 6, 7, 1, 4, 5, 6, 7]
[ 2  8 10 12 14]


In [91]:
b.shape
c.shape

(5,)

In [94]:
#Multiplication of 2 arrays

z3 = b*c
print(z3)

#Lets see multiplication of different array size, hope we will see the error :-p
u = np.array([1,2,3])
v = np.array([6,7])
z4 = u*v
print(z4)

[ 2 16 25 54 70]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 